### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bootstraponline** [linkedin/dex-test-parser#15]
It'd be great to have a new release now that https://github.com/linkedin/dex-test-parser/pull/14 has been merged.

**Comment by rdiaz82** [comment]
It would be great a new release!!

**Comment by drewhannay** [comment]
This is definitely on our radar. @kkoser is working on the other two open issues - current plan is to do a release after those are addressed.

**Comment by rdiaz82** [comment]
Hi! do you have any plans to update the release version after fix all opened tickets? It would be great have a new library version with all these fixes

**Comment by bootstraponline** [comment]
Agreed, we'd love to pull the new fixes into Flank.

**Comment by drewhannay** [comment]
Ah, I thought I had done this already but I think I only released Test Butler and dexmaker 😅 

I'll take care of this tomorrow, my apologies.

**Comment by drewhannay** [comment]
I just published [2.0.0](https://github.com/linkedin/dex-test-parser/releases/tag/2.0.0), enjoy 😉

**Comment by bootstraponline** [comment]
Thank you!!
