### ISSUE TITLE
Upload parser.jar as part of the release

### ISSUE THREAD

**Issue by kirillzh** [linkedin/dex-test-parser#2]

**Comment by drewhannay** [comment]
Can you clarify what you're looking for here? That file should already be included in the release on jcenter / bintray:

https://bintray.com/linkedin/maven/parser/1.0.0#files/com/linkedin/dextestparser/parser/1.0.0

**Comment by kirillzh** [comment]
Oh, I'm talking about release [here](https://github.com/linkedin/dex-test-parser/releases/tag/1.0.0), on GitHub. Since one of your usage examples uses jar file, it's unclear where to get this jar from. In such cases I think usually executables are included in repo releases.
Or it might be easier to add this [link](https://bintray.com/linkedin/maven/download_file?file_path=com%2Flinkedin%2Fdextestparser%2Fparser%2F1.0.0%2Fparser-1.0.0-all.jar) to README.

**Comment by drewhannay** [comment]
Ah, gotcha. Yeah, we don't usually upload binaries to github releases, but adding the bintray link to README.md would work.
