### ISSUE TITLE
Filter default methods

### ISSUE THREAD

**Issue by winterDroid** [linkedin/dex-test-parser#20]
We have a weird test structure where we have Kotlin interfaces implementing test methods as default implementations.  The actual test classes implement those interfaces. Unfortunately the default methods in the interfaces are also returned by `findTestMethods`.

**Comment by winterDroid** [comment]
This could be fixed eg by filtering invalid test methods. The invalid generated test methods are static and take an argument.

**Comment by winterDroid** [comment]
Seems to be the same as #13 just with default methods

**Comment by bootstraponline** [comment]
If you could provide a minimal reproducible example, that'd be helpful in resolving this.

**Comment by winterDroid** [comment]
Sure. It is just a default interface method annotated with `@Test` as
```
interface MyTestInterface {
  @Test
  fun myTestMethod() {
    assertTrue() 
  } 
} 
```

**Comment by kkoser** [comment]
I agree that we should be filtering these out - interfaces are not instantiable, and I tested this with the standard adb instrument and it does not find this class by default. I'll look at how we can filter this out, not sure what the representation of default methods is in the dex format atm

**Comment by winterDroid** [comment]
Any updates? :)

**Comment by kkoser** [comment]
This was fixed with #22 . I think we still need to do a release that contains that fix though - @drewhannay can you help out with that?

**Comment by drewhannay** [comment]
2.0.1 has been released

**Comment by winterDroid** [comment]
Great thanks @drewhannay!
