### ISSUE TITLE
Maven central?

### ISSUE THREAD

**Issue by bootstraponline** [linkedin/dex-test-parser#30]
It'd be nice if the artifact was published to maven central.

```
Could not find com.linkedin.dextestparser:parser:2.0.1.
Searched in the following locations:
  - https://maven-central.storage-download.googleapis.com/repos/central/data/com/linkedin/dextestparser/parser/2.0.1/parser-2.0.1.pom
  - https://maven-central.storage-download.googleapis.com/repos/central/data/com/linkedin/dextestparser/parser/2.0.1/parser-2.0.1.jar
Required by:
    project :
```

I think bintray can even automate this for you:
https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/

**Comment by drewhannay** [comment]
I agree it would be nice, but at the moment we have a somewhat standardized process for publishing open source artifacts from LinkedIn and it would be a bigger ask to add maven central to that pipeline. It might happen someday but I don't think it'll be prioritized in the near future
