### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bootstraponline** [linkedin/dex-test-parser#33]
Now that https://github.com/linkedin/dex-test-parser/pull/32 has been merged, it'd be great to have a new release. 😁

**Comment by hongbinh** [comment]
We might wait a little for #36  to go in before make a new release, thanks for your patience!

**Comment by drewhannay** [comment]
Version [2.1.0](https://github.com/linkedin/dex-test-parser/releases/tag/2.1.0) has been released :)
