### ISSUE TITLE
Multidex abstract test class issue

### ISSUE THREAD

**Issue by lukaville** [linkedin/dex-test-parser#45]
Hi,
We use this library for extracting tests to run from apks and we have recently noticed that parsed test count is not stable. We run it on CI and sometimes a few test methods are not parsed. After some investigation, it turns out that these methods are defined in base test classes.

I checked two apks: the first one where we don't have tests from a base class and the second one where these tests were parsed successfully. Hashes of the apks are different but if you unpack them and compare the hashes of the contents they are absolutely identical. Hashes of all the dex files are the same. The only difference that I found is the order of dex files how they appear in zip archive :)

So the problem is that base class was defined in `classes4.dex` and the concrete implementation is in `classes2.dex`. The order of the dex files in the archive is completely random each time when you package the apk. Not sure is this a violation of dex specification or not because in the [specs](https://source.android.com/devices/tech/dalvik/dex-format.html) there is no info about multidex and I can't find any specs specifically for multidex. 

We use AGP 3.5.1. Has anyone encountered this problem?
Looks like we can't rely on the order of classes/superclasses when we have multiple dex files, so we need to have multiple passes. What do you think about it? I will create a PR soon with the fixes

**Comment by kkoser** [comment]
Thanks for raising this! I could have sworn multidex made some guarantees on the ordering of dex files, but looking back at thee docs looks like its only for the main dex file :( Appreciate you raising the PR! I'm going to try and take a look this weekend
