### ISSUE TITLE
Inherited method annotations are missing

### ISSUE THREAD

**Issue by inez** [linkedin/dex-test-parser#69]
Consider this change:
```
diff --git a/test-app/src/androidTest/java/com/linkedin/parser/test/junit4/java/AbstractTest.java b/test-app/src/androidTest/java/com/linkedin/parser/test/junit4/java/AbstractTest.java
index 81dc312..70b1018 100644
--- a/test-app/src/androidTest/java/com/linkedin/parser/test/junit4/java/AbstractTest.java
+++ b/test-app/src/androidTest/java/com/linkedin/parser/test/junit4/java/AbstractTest.java
@@ -1,5 +1,6 @@
 package com.linkedin.parser.test.junit4.java;
 
+import org.junit.Ignore;
 import org.junit.Test;
 
 import static org.junit.Assert.assertTrue;
@@ -7,6 +8,7 @@ import static org.junit.Assert.assertTrue;
 public abstract class AbstractTest {
 
     @Test
+    @Ignore
     public void abstractTest() {
         assertTrue(true);
     }
```
in the output `com.linkedin.parser.test.junit4.java.ConcreteTest#abstractTest` should have both `org.junit.Ignore` and `org.junit.Test` applied (present in `annotations` property), but it actually has none.

**Comment by inez** [comment]
Seems like this change potentially fixes it:
```
diff --git a/parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt b/parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt
index 4ae1261..1e4e958 100644
--- a/parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt
+++ b/parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt
@@ -128,7 +128,7 @@ private fun createAllTestMethods(
 
                         TestMethod(
                                 testName = className + method.testNameWithoutClass,
-                                annotations = onlyParentAnnotations + childClassAnnotations
+                                annotations = onlyParentAnnotations + childClassAnnotations + method.annotations.filter { it.inherited }
                         )
                     }
                     .toSet()
```

**Comment by drewhannay** [comment]
I think the fix may be more complicated than that unfortunately. Consider this case:

```java
public abstract class AbstractTest {

    @Test
    @Ignore
    public void abstractTest() {
        assertTrue(true);
    }
}

public class ConcreteTest extends AbstractTest {

    @Override
    @Test
    public void abstractTest() {
        super.abstractTest();
    }
}
```

In this case, if I run all tests in `ConcreteTest`, the `abstractTest` method is NOT ignored (overriding the method and adding `@Test` takes precedence over the `@Ignore` in the abstract class).

I do agree it looks like there's a bug to fix for the case when the abstract method is not overridden though.

**Comment by kkoser** [comment]
I'm working on a solution that I think will cover all the cases here - the general gist is that you need to differentiate overridden methods from non-overridden ones, and choose what annotations to pass accordingly. Test cases for this have revealed some other bugs which I'm workin on fixing, should have a PR by EOD. Sorry for the delay!

**Comment by kkoser** [comment]
#71 should fir this, if you could test and confirm @inez that would be great!

**Comment by inez** [comment]
@kkoser I took a brief look yesterday and it looks valid - over next few weeks I will try to implement it (dex-test-parser) as an alternative parser to the one we are using now (apktool based one) - and continuously compare results to find out about differences.
